# 
# Euclideandistances and cosine sims of dat generated by PRNGs in N-D !

# Illustrated in 2 and 3 D

library(ggplot2)

# 2D example

# rnorm

# Sample data (10K points)
set.seed(42)
df <- data.frame(
  x = rnorm(10000),
  y = rnorm(10000)
)

# Convert to matrix
mat <- as.matrix(df)  # n x 2

# ---- 1. Euclidean distances ----
dists <- dist(mat)  # returns "dist" object with N choose 2 entries

# ---- 2. Cosine similarity ----
norm_mat <- mat / sqrt(rowSums(mat^2))  # normalize rows
cosine_sim <- tcrossprod(norm_mat)      # cosine similarity matrix (n x n)
cosine_sim_vals <- cosine_sim[upper.tri(cosine_sim)]

# data
ggplot(
  data = df
) + geom_point(aes(x = x, y = y), colour = "red")

Sys.sleep(5)

# ---- Histogram plotting ----

ggplot(data.frame(dist = as.vector(dists)), aes(dist)) +
  geom_histogram(bins = 100, fill = "blue", alpha = 0.6) +
  ggtitle("Histogram of Pairwise Euclidean Distances")

Sys.sleep(5)

ggplot(data.frame(cos_sim = cosine_sim_vals), aes(cos_sim)) +
  geom_histogram(bins = 100, fill = "green", alpha = 0.6) +
  ggtitle("Histogram of Pairwise Cosine Similarities")


#runif
df <- data.frame(
  x = runif(10000),
  y = runif(10000)
)

# make it so both dists have "spherical" sym :)
df$x <- df$x - 0.5
df$y <- df$y - 0.5
# Convert to matrix
mat <- as.matrix(df)  # n x 2

# ---- 1. Euclidean distances ----
dists <- dist(mat)  # returns "dist" object with N choose 2 entries

# ---- 2. Cosine similarity ----
norm_mat <- mat / sqrt(rowSums(mat^2))  # normalize rows
cosine_sim <- tcrossprod(norm_mat)      # cosine similarity matrix (n x n)
cosine_sim_vals <- cosine_sim[upper.tri(cosine_sim)]

# data
ggplot(
  data = df
) + geom_point(aes(x = x, y = y), colour = "red") + 
  ggtitle("10000 random 2D points drawn from uniform dist")

Sys.sleep(5)

# ---- Histogram plotting ----

ggplot(data.frame(dist = as.vector(dists)), aes(dist)) +
  geom_histogram(bins = 100, fill = "blue", alpha = 0.6) +
  ggtitle("Histogram of Pairwise Euclidean Distances - Uniform dist")

Sys.sleep(5)

ggplot(data.frame(cos_sim = cosine_sim_vals), aes(cos_sim)) +
  geom_histogram(bins = 100, fill = "green", alpha = 0.6) +
  ggtitle("Histogram of Pairwise Cosine Similarities - Uniform dist")

